## Boolean Masking

We can create an array of boolean values, an use that array mask some of the rows of another array

In [6]:
import numpy as np

x = np.zeros((10, 3))

for i in range(10):
    for j in range(3):
        x[i,j] = (i+1)*(j+1)

print("Original Array:")
print(x)

mask = np.ones(10, dtype=bool) # Create an array of boolean values (all true)
mask[5:10] = False             # Change some of those values to false

print("Masked array:\n", x[mask, :])

Original Array:
[[ 1.  2.  3.]
 [ 2.  4.  6.]
 [ 3.  6.  9.]
 [ 4.  8. 12.]
 [ 5. 10. 15.]
 [ 6. 12. 18.]
 [ 7. 14. 21.]
 [ 8. 16. 24.]
 [ 9. 18. 27.]
 [10. 20. 30.]]
Masked array:
 [[ 1.  2.  3.]
 [ 2.  4.  6.]
 [ 3.  6.  9.]
 [ 4.  8. 12.]
 [ 5. 10. 15.]]
