In this notebook, we follow a walkthrough of numerical operations numpy provides, along with an accompanying visualizaitons. Please check out the inspiration behind this notebook at the following link: https://jalammar.github.io/visual-numpy/ 

In [3]:
import numpy as np

random_list = [1,2,3]

rand = np.array(random_list)

print(rand)

# Notice that the values are horizontal

[1 2 3]


We can perform standard operations to `1 x A` matrices (arrays) like normal

In [5]:
print(rand + rand)
print(3*rand)
print(-1*rand / rand)

[2 4 6]
[3 6 9]
[-1. -1. -1.]


# Two dimensional arrays

In [18]:
list1 = [1,2,3]
list2 = [4,5,6]

two_D_list = [list1, list2]

arr = np.array(two_D_list)

print(arr)

# Notice that now we have one list stacked on top of the other
# We have 2 rows and 3 columns


[[1 2 3]
 [4 5 6]]


In [21]:
############ Array Arithmetic ########

# Addition two matrices
a = np.ones((3,4))
b = 2 * np.ones((3,4))
print(a + b)
print(a*b)

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [20]:
# Addition of a 1-d and 2d array (adds the 1-d array to each row of 2-d array)
x = np.array([34,12])
y = np.ones((4,2))
z = x + y
print(z)
# Should have be 3 x 2 matrix of [35,13]'s

[[35. 13.]
 [35. 13.]
 [35. 13.]
 [35. 13.]]


## Matrix Multiplcication

In `NumPy`, matrix multiplication is implemented **semantically** as opposed to **syntactically**

Namely, instead of the product of A x B being `A * B`, the product A x B is defined by the 

#### **`dot product`:**

`A.dot(B)`

In [31]:
# Matrix Multiplication

A = np.array([3,5,10])
print(A.shape) # (1, 3)

W = np.array([[1,2,4,5],[0,0,1,0], [2,2,2,2]])
print(W.shape) # (3, 4)

print("A:", A)
print()
print("W:\n", W)
print()
print("A.dot(W)\t\t", A.dot(W))

print("BOOM!")

(3,)
(3, 4)
A: [ 3  5 10]

W:
 [[1 2 4 5]
 [0 0 1 0]
 [2 2 2 2]]

A.dot(W)		 [23 26 37 35]
BOOM!


**Shape**

* The shape of a list is `1 x n`, where `n` is the number of elements in that list


* The shape of a 2d array is `m x n` where
    * `m` is the number of rows
    * `n` is the number of columns

In [9]:
shape = (3,2)
x = np.ones(shape)
print(x)
# x will be an array with 3 rows and 2 columns, essentially a list of 3 2-dimensional vectors

[[1. 1.]
 [1. 1.]
 [1. 1.]]


Sometimes when indexing an array, we will get a list embedded in another list like:
```python
x = [[1,23,4]]
```

To grab the list [1,23,4], we index x = [0,]

In [14]:
y = np.random.random((1,4))
print(y)
print(y[0])
print(y[0],)

[[0.10014846 0.7169905  0.41887831 0.56779329]]
[0.10014846 0.7169905  0.41887831 0.56779329]
[0.10014846 0.7169905  0.41887831 0.56779329]


In [17]:
# Creating 3-d arrays
z = np.zeros((2,3,4))
# This will look like 2 3x4 matrices
print(z)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


Notice that which direction the first indice *indexes* depends on the shape of the nd-array
* If shape is 1d - indexes in the x direction
* If shape is 2d - indexes in the y direction
* If shape is 3d - indexes in the z direction

# Splicing

In [35]:
A = np.array([[1,2,3], [2,3,4]])

print(A.shape) # shape (2,3)

print(A[1,2]) # should be 4

# Grabbing a single column
print(A[:,1]) # should be (2,3)
print(A[:,1].shape) # (2,1)

# Grabbing a single row
print(A[1,:])
print(A[1,:].shape) # (1,3)

print(A[:,])
print(A[1])

(2, 3)
4
[2 3]
(2,)
[2 3 4]
(3,)
[[1 2 3]
 [2 3 4]]
[2 3 4]


Observations:
* When the splice returns a 1d array, it has the shape `(n,)`
* When grabbing a single column or row, it always returns a `row vector of shape (n,)`