# NumPy
In this notebook we will explore the functionalities `numpy` module has when working with n-dimensional arrays. In particular, we will learn how to apply functions to arrays (without for-loops), and understand array properties

**References**
* [NumPy Math Functions](https://numpy.org/doc/stable/reference/routines.math.html)

## Object and Properties

In [ ]:
import numpy as np

x = np.array([[3,4,5],[5,12,13]])

print(type(x)) # array, zeroes, empty creates a "ndarray" object
print(x)


In [ ]:
attr_and_methods = [a for a in dir(x) if '__' not in a]
print(attr_and_methods) # printout out all the attributes and methods of ndarray

In [11]:
def print_properties(x):
    print(x.ndim) # number of axes
    print(x.shape) # number of rows and columns
    print(x.size) # number of elemtns in array
    print(x.dtype)
    print(x.itemsize)

In [ ]:
print(x)
print_properties(x)
print("---")
y =np.arange(0,15,1).reshape(3,5)
print(y)
print_properties(y)

In [17]:
# Can create numpy array from regular list 
lst = [1,2.,3]

array_numpy = np.array(lst)

print(type(lst[0]))
print(type(array_numpy[0]))

<class 'int'>
<class 'numpy.float64'>


In [21]:
array = [
    [1,2,3,4,5],
    [5,4,3,2,1],
    [0,0,0,0,0],
    ]

x = np.array(array)
print(x)
print(x[1,1])

[[1 2 3 4 5]
 [5 4 3 2 1]
 [0 0 0 0 0]]
4


In [ ]:
x = np.zeros((3,3))
y = np.ones((3,3))
z = np.empty((4,3))
print(f"""
zeroes:\n{x}
ones:\n{y}
empty:\n{z}
""")

## Sequences and Operations

**Creating sequences**  
To create sequences of numbers:
1. Use `arange(start, stop (noninclusive), step)`
    * good with integers, and not needing stop
2. Use `linspace(start, stop (inclusive), num_samples)`
    * good with floaitng points, and including endpoint


In [30]:
x = np.arange(0,2, .5)
y = np.linspace(0,2,5)
print(x,y)

[0.  0.5 1.  1.5] [0.  0.5 1.  1.5 2. ]


**Operations on ndarrays**
To add, multiply, subtract, and divide a `scalar` to a `vector` (array), you will have to use Numpy functions:

`np.add, np.subract, np.multiply, np.divide`

In [54]:
x = np.arange(1,6)
Y = 5
print(np.add(x,Y))
print(np.multiply(x,Y))

# notice for noncommutative operators order matters!
print(np.divide(Y,x))
print(np.divide(Y,x) == np.divide(x,Y)) # relation operators are overloaded to be elementwise

print(np.subtract(x,Y))



[ 6  7  8  9 10]
[ 5 10 15 20 25]
[5.         2.5        1.66666667 1.25       1.        ]
[False False False False  True]
[-4 -3 -2 -1  0]


In [33]:
# Arithmetic operators on arrays are applied elementwise

shots_taken = np.array([5,1,3])
goals_scored = np.array([1,0,2])

shot_accuracy = goals_scored / shots_taken

print(shot_accuracy)

percent_shots = shot_accuracy *100
print(percent_shots)

[0.2        0.         0.66666667]
[20.          0.         66.66666667]


In [34]:
# Subtracting a number from an ndarray
ndarray = np.linspace(-1,1,10)
print(ndarray)

b = 1 #shifting up by one
b_vector = np.ones(len(ndarray)) * b
ndarray += b_vector

print(ndarray)


[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


In [35]:
# calculating sums
grocery_prices = np.array([1,2,3,4,2,3,15])
sum = grocery_prices.sum()
min = grocery_prices.min()
max = grocery_prices.max()
print(sum, min, max)

30 1 15


**Universal Functions** 
Functions like `sin(x), cos(x)`, which operate elementwise on arrays and are built into NumPy module

In [ ]:
import matplotlib
import matplotlib.pyplot as plt

x = np.linspace(-2*np.pi, 2*np.pi, 1000)

plt.figure(figsize=(4,2))
plt.plot(x, np.sin(x))

**adding a number**

In [51]:
x = np.arange(4)
print(x)
x = np.add(x,2)
print(x)

[0 1 2 3]
[2 3 4 5]


In [41]:
X = np.arange(4)

print(np.exp(X)) # calculates exponential of each element in range(4)
print(np.sqrt(X))

Y = np.arange(5,9)

Z = np.add(X,Y)
print(Z)

[ 1.          2.71828183  7.3890561  20.08553692]
[0.         1.         1.41421356 1.73205081]
[ 5  7  9 11]


**filtering an array**

In [50]:
# where(condition, [x,y]) - x,y are array_like
x = np.array([1,2.,-1,-5,10,0])
y = np.where(x>=0, x, 0)
print(y)

[ 1.  2.  0.  0. 10.  0.]
